### ISSUE TITLE
Slow transition even though transition duration is set to 0.15s

### ISSUE THREAD

**Issue by motion-work** [maoberlehner/transition-to-height-auto-with-vue#16]
![slow_transition](https://user-images.githubusercontent.com/11538632/80012523-bb137c80-84cd-11ea-8a52-63fef834269c.gif)

```css
<style>
.expand-enter-active,
.expand-leave-active {
  transition: height 0.15s ease-in-out, opacity 0.15s ease-in-out;
  overflow: hidden;
}
.expand-enter,
.expand-leave-to {
  opacity: 0;
  height: 0;
}
</style>
```

Did anyone have this issue too?
